export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS'
export type CONNECTION_SUCCESS = typeof CONNECTION_SUCCESS

export const CONNECTION_ERROR = 'CONNECTION_ERROR'
export type CONNECTION_ERROR = typeof CONNECTION_ERROR

export const CONNECT = 'CONNECT'
export type CONNECT = typeof CONNECT
